import { expect, test } from '@playwright/test'
import { authenticateThroughLogin, expectNoDocumentOverflow } from './fixtures'

test.describe('responsive essential workflows', () => {
  test('admin mobile shell and essential cards fit at 390px', async ({ page }) => {
    await page.setViewportSize({ width: 390, height: 844 })
    const rejected = await authenticateThroughLogin(page, 'admin')

    await page.goto('/transactions')
    await expect(page.getByRole('heading', { name: 'Transacciones', level: 1 })).toBeVisible()
    const createTransaction = page.getByRole('button', { name: 'Nueva transacción' })
    await expect(createTransaction).toBeVisible()
    const transactionCard = page.locator('.transaction-mobile-card').filter({ hasText: 'Venta shampoo' })
    await expect(transactionCard).toBeVisible()
    await expect(transactionCard).toContainText('+$18.500')

    const selector = transactionCard.getByRole('checkbox', { name: 'Seleccionar Venta shampoo' })
    const selectorBox = await selector.locator('..').boundingBox()
    expect(selectorBox?.width).toBeGreaterThanOrEqual(44)
    expect(selectorBox?.height).toBeGreaterThanOrEqual(44)

    await transactionCard.getByRole('button', { name: 'Ver detalle de Venta shampoo' }).click()
    const moveUp = transactionCard.getByRole('button', { name: 'Mover Venta shampoo hacia arriba' })
    const moveDown = transactionCard.getByRole('button', { name: 'Mover Venta shampoo hacia abajo' })
    await expect(moveUp).toBeVisible()
    await expect(moveDown).toBeVisible()
    expect((await moveUp.boundingBox())?.height).toBeGreaterThanOrEqual(44)
    expect((await moveDown.boundingBox())?.height).toBeGreaterThanOrEqual(44)
    await expect(transactionCard.getByTitle('Anular')).toBeVisible()

    await selector.check()
    await page.getByRole('checkbox', { name: 'Seleccionar Servicio manos' }).check()
    const selectionBar = page.getByRole('region', { name: 'Acciones de selección' })
    await expect(selectionBar).toContainText('2 seleccionadas')
    await expect(selectionBar.getByRole('button', { name: 'Agrupar' })).toBeVisible()

    const groupedCard = page.locator('.transaction-mobile-card[data-row-kind="group"]')
    await groupedCard.getByRole('button', { name: 'Ver detalle de Turno combinado' }).click()
    await expect(groupedCard.getByRole('button', { name: 'Mover Turno combinado hacia arriba' })).toBeDisabled()
    await expect(groupedCard.locator('.transaction-group-member').getByText('Color y corte')).toBeVisible()
    await expect(groupedCard.locator('.transaction-group-member').getByText('Nutrición capilar')).toBeVisible()
    await expectNoDocumentOverflow(page)

    await page.locator('.responsive-page-body').evaluate(element => { element.scrollTop = element.scrollHeight })
    await expect(createTransaction).toBeVisible()

    await page.setViewportSize({ width: 320, height: 800 })
    await page.goto('/transactions')
    await expect(page.getByRole('button', { name: 'Nueva transacción' })).toBeVisible()
    await expect(page.locator('.transaction-mobile-card').filter({ hasText: 'Venta shampoo' })).toContainText('+$18.500')
    await expectNoDocumentOverflow(page)

    await page.goto('/inventory')
    const inventoryCard = page.locator('.data-card').filter({ hasText: 'Shampoo nutritivo' })
    await expect(inventoryCard).toBeVisible()
    await inventoryCard.locator('summary').click()
    await expect(inventoryCard.getByTitle('Editar producto')).toBeVisible()
    await expect(inventoryCard.getByTitle('Ver lotes')).toBeVisible()
    await expectNoDocumentOverflow(page)

    await page.goto('/cuentas')
    await expect(page.getByText('Distribuidora Norte')).toBeVisible()
    await expect(page.getByRole('button', { name: 'Registrar pago' })).toBeVisible()
    await expectNoDocumentOverflow(page)

    await page.goto('/reports')
    await expect(page.locator('.responsive-tabs')).toContainText('Financiero')
    await expect(page.locator('.responsive-tabs')).toContainText('Comisiones')
    await expect(page.locator('.responsive-tabs')).toContainText('Utilidad')
    await expect(page.locator('.responsive-tabs')).toContainText('Costos')
    await expect(page.locator('.responsive-tabs')).toContainText('Balance')
    await expect(page.locator('.responsive-tabs')).toContainText('Sueldos')
    await expect(page.getByRole('navigation', { name: 'Navegación principal móvil' })).toBeVisible()
    await expectNoDocumentOverflow(page)
    expect(rejected).toEqual([])
  })

  test('employee mobile navigation excludes accounts and guard remains active', async ({ page }) => {
    await page.setViewportSize({ width: 390, height: 844 })
    const rejected = await authenticateThroughLogin(page, 'employee')
    await page.goto('/transactions')

    await expect(page.getByRole('link', { name: 'Transacciones' })).toBeVisible()
    await expect(page.getByRole('link', { name: 'Cuentas' })).toHaveCount(0)
    await page.goto('/cuentas')
    await expect(page).toHaveURL(/\/dashboard$/)
    expect(rejected).toEqual([])
  })

  test('quick funnel keeps mobile progress, ticket, scrolling, and actions usable', async ({ page }) => {
    await page.setViewportSize({ width: 390, height: 844 })
    const rejected = await authenticateThroughLogin(page, 'admin')
    await page.goto('/transactions/cargar')

    const content = page.getByTestId('quick-funnel-content')
    await expect(page.getByRole('progressbar', { name: /Paso 1 de 4: Tipo/ })).toBeVisible()
    await expect(page.getByRole('button', { name: 'Ver lista de transacciones' })).toBeVisible()
    await page.getByRole('button', { name: /Ingreso/ }).click()
    await expect(page.getByRole('progressbar', { name: /Paso 2 de 6: Detalle/ })).toBeVisible()
    await expect.poll(() => content.evaluate(element => element.scrollTop)).toBe(0)
    await expect.poll(() => page.locator('.quick-funnel-income-tabs').evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true)

    await page.getByRole('button', { name: /Corte E2E/ }).click()
    const mobileFooter = page.locator('.quick-funnel__actions--mobile')
    const primary = mobileFooter.getByRole('button', { name: /Continuar/ })
    await expect(primary).toBeVisible()

    await page.setViewportSize({ width: 390, height: 500 })
    const contentHeightBefore = await content.evaluate(element => element.clientHeight)
    await page.getByRole('button', { name: /Resumen del ticket/ }).click()
    await expect(page.getByRole('button', { name: 'Cerrar resumen del ticket' })).toBeVisible()
    await expect(primary).toBeVisible()
    expect(await content.evaluate(element => element.clientHeight)).toBe(contentHeightBefore)
    await expectNoDocumentOverflow(page)
    await page.getByRole('button', { name: 'Cerrar resumen del ticket' }).click()

    await content.evaluate(element => { element.scrollTop = element.scrollHeight })
    expect(await content.evaluate(element => element.scrollTop)).toBeGreaterThan(0)
    await primary.click()
    await expect(page.getByRole('progressbar', { name: /Paso 3 de 6: Monto/ })).toBeVisible()
    await expect.poll(() => content.evaluate(element => element.scrollTop)).toBe(0)

    await mobileFooter.getByRole('button', { name: /Continuar/ }).click()
    await expect(page.getByRole('progressbar', { name: /Paso 4 de 6: Ajustes/ })).toBeVisible()
    await expect.poll(() => content.evaluate(element => element.scrollTop)).toBe(0)
    await mobileFooter.getByRole('button', { name: /Continuar/ }).click()
    await expect(page.getByRole('progressbar', { name: /Paso 5 de 6: Pago/ })).toBeVisible()
    await expect.poll(() => content.evaluate(element => element.scrollTop)).toBe(0)
    await expect(mobileFooter.getByRole('button', { name: /Confirmar y registrar/ })).toBeVisible()
    await expectNoDocumentOverflow(page)

    await page.setViewportSize({ width: 613, height: 800 })
    await page.goto('/transactions/cargar')
    await expect(page.getByRole('progressbar', { name: /Paso 1 de 4: Tipo/ })).toBeVisible()
    await expect(page.locator('.quick-funnel__desktop-stepper')).toBeHidden()
    await expectNoDocumentOverflow(page)

    await page.setViewportSize({ width: 320, height: 800 })
    await page.goto('/transactions/cargar')
    const typeCards = page.locator('.quick-funnel-type-card')
    await expect(typeCards).toHaveCount(4)
    const firstBox = await typeCards.nth(0).boundingBox()
    const secondBox = await typeCards.nth(1).boundingBox()
    const thirdBox = await typeCards.nth(2).boundingBox()
    expect(Math.abs((firstBox?.y ?? 0) - (secondBox?.y ?? 0))).toBeLessThan(2)
    expect((thirdBox?.y ?? 0)).toBeGreaterThan((firstBox?.y ?? 0))

    await page.getByRole('button', { name: /Gasto/ }).click()
    await expect(page.getByRole('progressbar', { name: /Paso 2 de 4: Detalle/ })).toBeVisible()
    await page.getByRole('button', { name: 'Alquiler' }).click()
    await mobileFooter.getByRole('button', { name: /Continuar/ }).click()
    await expect(page.getByRole('progressbar', { name: /Paso 3 de 4: Monto/ })).toBeVisible()
    await expect.poll(() => content.evaluate(element => element.scrollTop)).toBe(0)
    await page.getByPlaceholder('0').fill('25000')
    await expect(mobileFooter.getByRole('button', { name: /Confirmar y registrar/ })).toBeVisible()
    await expectNoDocumentOverflow(page)
    expect(rejected).toEqual([])
  })

  test('desktop keeps the sidebar and table presentation', async ({ page }) => {
    await page.setViewportSize({ width: 1280, height: 800 })
    const rejected = await authenticateThroughLogin(page, 'admin')
    await page.goto('/transactions')

    await expect(page.locator('.sidebar')).toBeVisible()
    await expect(page.locator('.data-table__table')).toBeVisible()
    await expect(page.locator('.data-table__table button[draggable="true"]').first()).toBeVisible()
    await expect(page.locator('.transaction-mobile-card')).toHaveCount(0)
    await expect(page.getByRole('navigation', { name: 'Navegación principal móvil' })).toBeHidden()
    await expectNoDocumentOverflow(page)

    await page.goto('/transactions/cargar')
    await expect(page.locator('.quick-funnel__desktop-stepper')).toBeVisible()
    await page.getByRole('button', { name: /Ingreso/ }).click()
    const desktopTicket = page.locator('.quick-ticket')
    await expect(desktopTicket).toBeVisible()
    expect((await desktopTicket.boundingBox())?.width).toBeCloseTo(300, 0)
    await expect(desktopTicket.locator('.quick-ticket__mobile-heading')).toBeHidden()
    await expect(page.locator('.sidebar')).toBeVisible()
    expect(rejected).toEqual([])
  })

  test('small and breakpoint widths have no document overflow', async ({ page }) => {
    await page.setViewportSize({ width: 320, height: 800 })
    const rejected = await authenticateThroughLogin(page, 'admin')
    for (const width of [320, 768]) {
      await page.setViewportSize({ width, height: 800 })
      await page.goto('/reports')
      await expect(page.getByRole('heading', { name: 'Reportes', level: 1 })).toBeVisible()
      await expectNoDocumentOverflow(page)
    }
    expect(rejected).toEqual([])
  })
})
